name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: auth
          POSTGRES_PASSWORD: auth
          POSTGRES_DB: auth_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U auth -d auth_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env
